--CANCELLATION DETAILS
 create table CANCELLATION_DETAILS(
 CANCELLATION_ID int primary key,
 CANCELLATION_CODE varchar,
 AMOUNT_REFUND numeric,
 AMOUNT_DEDUCT numeric,
 CANCELLATION_DATE&TIME DATETIME,
 CANCELLATION_REASON varchar,
 foreign key(CANCELLATION_CODE) references TICKET_DETAILS(Ticket_code)
 );