--TRAVEL DETAILS
 create table TRAVEL_DETAILS(
 TRAVEL_ID int primary key,
 TRAVEL_ROUTE int,
 TRAVEL_AIRCRAFT int,
 CONSTRAINT TRAVEL_FK Foreign key(TRAVEL_ROUTE) references ROUTE(ROUTE_ID),
 CONSTRAINT TRAVEL_FK_2 Foreign key(TRAVEL_AIRCRAFT) references AIRCRAFT_DETAILS(AC_ID)
  );
